# docker-compose.yml

version: '3.8'

services:
  fast-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn  app.main:app --host 0.0.0.0 --reload
    volumes:
      - ./app:/code/app
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
        - my_network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${SERVICE_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
    external: true

volumes:
    mysql:
      driver: local

