# docker-compose.yml

version: '3.8'

services:
  fast-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
       - .:/app/app
    ports:
      - 8000:8000