CIF_ID_TEST = '123'  # cif_id dùng tạm để test


IDENTITY_DOCUMENT_TYPE_IDENTITY_CARD = 'CMND'
IDENTITY_DOCUMENT_TYPE_CITIZEN_CARD = 'CCCD'
IDENTITY_DOCUMENT_TYPE_PASSPORT = 'HC'

IDENTITY_DOCUMENT_TYPE = {
    IDENTITY_DOCUMENT_TYPE_IDENTITY_CARD: 'Chứng minh nhân dân',
    IDENTITY_DOCUMENT_TYPE_CITIZEN_CARD: 'Căn cước công dân',
    IDENTITY_DOCUMENT_TYPE_PASSPORT: 'Hộ chiếu'
}
